import { COL_VENTS, COL_CARGO_A, COL_FLOOR_1, COL_GOLD, COL_TEAL, COL_PURPLE, COL_ATTATCH, COL_GOOD } from "resources/colours";

export enum ZONE_TYPE {
    SPACE='SPACE',
    ARMORY='ARMORY',
    ARMORY_VENT="ARMORY_VENT",
    BRIDGE='BRIDGE',
    BRIDGE_VENT='BRIDGE_VENT',
    CHURCH='CHURCH',

    CARGO_A='CARGO_A',
    CARGO_A_VENT='CARGO_A_VENT',

    BIOLOGY='BIOLOGY',

    SERVICE_TUNNELS='SERVICE_TUNNELS',
    REACTOR='REACTOR'
}

export const STRING_TO_ZONE_TYPE = new Map<string, ZONE_TYPE>();
STRING_TO_ZONE_TYPE.set('SPACE', ZONE_TYPE.SPACE);
STRING_TO_ZONE_TYPE.set('ARMORY', ZONE_TYPE.ARMORY);
STRING_TO_ZONE_TYPE.set('ARMORY_VENT', ZONE_TYPE.ARMORY_VENT);
STRING_TO_ZONE_TYPE.set('CHURCH', ZONE_TYPE.CHURCH);
STRING_TO_ZONE_TYPE.set('CARGO_A', ZONE_TYPE.CARGO_A);
STRING_TO_ZONE_TYPE.set('BRIDGE', ZONE_TYPE.BRIDGE);
STRING_TO_ZONE_TYPE.set('BRIDGE_VENT', ZONE_TYPE.BRIDGE_VENT);
STRING_TO_ZONE_TYPE.set('CARGO_A_VENT', ZONE_TYPE.CARGO_A_VENT);
STRING_TO_ZONE_TYPE.set('BIOLOGY', ZONE_TYPE.BIOLOGY);
STRING_TO_ZONE_TYPE.set('SERVICE_TUNNELS', ZONE_TYPE.SERVICE_TUNNELS);
STRING_TO_ZONE_TYPE.set('REACTOR', ZONE_TYPE.REACTOR);

export const ZONE_TYPE_TO_ZONE_NAME = new Map<ZONE_TYPE, string>();
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.SPACE, `${COL_PURPLE}Space|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.ARMORY, `${COL_ATTATCH}Armory|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.CHURCH, `${COL_GOLD}Cathederal|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.SERVICE_TUNNELS, `${COL_VENTS}Service Tunnels|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.BRIDGE, `${COL_CARGO_A}Bridge|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.BRIDGE_VENT, `${COL_VENTS}Bridge Connector|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.CARGO_A, `${COL_CARGO_A}Cargo|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.BIOLOGY, `${COL_TEAL}Genetics Lab|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.CARGO_A_VENT, `${COL_VENTS}Cargo Connector|r`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.ARMORY_VENT, `${COL_VENTS}Service Tunnels|r (Gas Facility)`);
ZONE_TYPE_TO_ZONE_NAME.set(ZONE_TYPE.REACTOR, `${COL_GOOD}Reactor|r`);
